In [181]:
import numpy as np

In [180]:
def grid_print(input):
    tmp = np.zeros([4,4], dtype=np.float32)
    for i in range(4):
        for j in range(4):
            tmp[i][j] = math.floor(input[i][j]*10)/10
    print(tmp)

In [186]:
gridworld = np.zeros([4,4], dtype=np.float32)
# print('k=0')
# grid_print(gridworld)

gridworld[:][:] = -1
gridworld[0][0] = 0
gridworld[3][3] = 0
# print('k=1')
# grid_print(gridworld)

for idx in range(105): 
    next_grid = np.zeros([4,4], dtype=np.float32)
    
    for i in range(4):
        for j in range(4):
            right, left, up, down, num_next_state = 0.0, 0.0, 0.0, 0.0, 0.0
            if (j < 3) : 
                right = gridworld[i][j+1]
                num_next_state = num_next_state + 1
            if (j > 0) : 
                left = gridworld[i][j-1]
                num_next_state = num_next_state + 1
            if (i > 0) :
                up = gridworld[i-1][j]
                num_next_state = num_next_state + 1
            if (i < 3 ) :
                down = gridworld[i+1][j]
                num_next_state = num_next_state + 1
            next_grid[i][j] = (-1.0+(right+left+up+down)/num_next_state)
    next_grid[0][0] = 0
    next_grid[3][3] = 0
    
    gridworld = next_grid

#     print('k=', idx+2)
#     grid_print(gridworld)
    
    if (idx+2) == 10:
        print('k=', idx+2)
        grid_print(gridworld)
        
    if (idx+2) == 100:
        print('k=', idx+2)
        grid_print(gridworld)
    

k= 10
[[ 0.  -5.8 -7.9 -8.3]
 [-5.8 -7.5 -8.1 -7.9]
 [-7.9 -8.1 -7.5 -5.8]
 [-8.3 -7.9 -5.8  0. ]]
k= 100
[[  0.  -11.  -15.5 -16.5]
 [-11.  -14.5 -16.  -15.5]
 [-15.5 -16.  -14.5 -11. ]
 [-16.5 -15.5 -11.    0. ]]
